[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
worldchain-mainnet = "https://worldchain-mainnet.g.alchemy.com/public"
worldchain-sepolia = "https://worldchain-sepolia.g.alchemy.com/public"

[etherscan]
worldchain = { key = "${WORLDSCAN_API_KEY}", url = "https://worldscan.org/api" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

# Gas reporting
[profile.gas]
inherits = "default"
optimizer = true
optimizer_runs = 1_000_000


